# Generated by Django 5.2 on 2025-06-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250620_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='report',
            name='reportid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescribe',
            name='employee',
            field=models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='prescribe',
            name='patient',
            field=models.ForeignKey(db_column='patientid', on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
