# Generated by Django 5.2 on 2025-06-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_phone_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescribe',
            options={'verbose_name_plural': 'Prescriptions'},
        ),
    ]
