# Generated by Django 5.2 on 2025-06-21 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_prescribe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='uploaded_on',
        ),
        migrations.AddField(
            model_name='report',
            name='date_uploaded',
            field=models.DateTimeField(db_column='date_uploaded', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pwd',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='prescribe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(db_column='patientid', on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
